name: Integration Tests (Docker)

on:
  pull_request:
    branches: ["main"]
    paths:
      - "PlantApp.Core/**"
      - "PlantApp.Tests/Integration/**"
      - "docker-compose.yml"
      - "Dockerfile"

  push:
    branches: ["main"]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Docker Integration Tests
        run: |
          docker compose down -v
          docker compose up --build --abort-on-container-exit

      - name: Cleanup
        if: always()
        run: docker compose down -v
